version: '3'

services:
  parser:
    # Дериктория где находится Dockerfile
    build: ./puppeteer
    # Команды которые необходимо запустить
#    command: xvfb-run --server-args="-screen 0 1024x768x24" npm start
    # Рестарт контейнера
    restart: unless-stopped
    # Указываем которые порты нелбходимо открыть local-port | container-port
    ports:
      - "3000:3000"
    # Переменныйе окруженя
    environment:
      - PORT=3000
      - HOST=http://realworld-docker.com